cat > template.yaml <<'YAML'
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tiny Serverless TODO API (Lambda + HTTP API + DynamoDB)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 256

Parameters:
  TableName:
    Type: String
    Default: TodosTable

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        GetItems:
          Type: HttpApi
          Properties:
            Path: /items
            Method: GET
        CreateItem:
          Type: HttpApi
          Properties:
            Path: /items
            Method: POST
        UpdateItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: PUT
        DeleteItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: DELETE
        Health:
          Type: HttpApi
          Properties:
            Path: /health
            Method: GET

  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: Base URL for the HTTP API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
YAML

